package com.example.katzu.ui.screens

import android.app.Activity
import android.util.Log
import androidx.compose.foundation.Image
import androidx.compose.foundation.background
import androidx.compose.foundation.border
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.rememberScrollState
import androidx.compose.foundation.shape.CircleShape
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.foundation.verticalScroll
import androidx.compose.material3.*
import androidx.compose.runtime.*
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.layout.ContentScale
import androidx.compose.ui.platform.LocalContext
import androidx.compose.ui.platform.testTag
import androidx.compose.ui.res.painterResource
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.automirrored.filled.ArrowBack
import androidx.credentials.Credential
import androidx.credentials.CredentialManager
import androidx.credentials.CustomCredential
import androidx.credentials.GetCredentialRequest
import androidx.credentials.exceptions.GetCredentialCancellationException
import androidx.credentials.exceptions.GetCredentialException
import androidx.credentials.exceptions.NoCredentialException
import com.example.katzu.R
import com.example.katzu.ui.theme.*
import com.example.katzu.util.AppLogger
import com.google.android.libraries.identity.googleid.GetGoogleIdOption
import com.google.android.libraries.identity.googleid.GetSignInWithGoogleOption
import com.google.android.libraries.identity.googleid.GoogleIdTokenCredential
import kotlinx.coroutines.launch
import kotlinx.coroutines.withTimeoutOrNull

private const val GOOGLE_WEB_CLIENT_ID = "754341831948-s76bt3vmcmnb7qvmcefbf1i8a16f11ss.apps.googleusercontent.com"

@Composable
fun SignInScreen(
    onSignInSuccess: (idToken: String, email: String, displayName: String?) -> Unit,
    onBack: (() -> Unit)? = null
) {
    val context = LocalContext.current
    val coroutineScope = rememberCoroutineScope()
    var isLoading by remember { mutableStateOf(false) }
    var statusMessage by remember { mutableStateOf<String?>(null) }
    var errorMessage by remember { mutableStateOf<String?>(null) }

    val credentialManager = remember { CredentialManager.create(context) }

    fun triggerGoogleSignIn() {
        AppLogger.i("SignInScreen", "triggerGoogleSignIn() invoked. Current isLoading=$isLoading")
        val activity = context as? Activity ?: run {
            AppLogger.e("SignInScreen", "context is not an Activity: $context")
            errorMessage = "حدث خطأ داخلي في تهيئة واجهة التسجيل."
            return
        }
        isLoading = true
        errorMessage = null
        statusMessage = "جاري فتح حسابات Google..."

        coroutineScope.launch {
            try {
                // Dynamically resolve default web client ID generated by google-services
                val defaultWebClientId = try {
                    val resId = context.getString(R.string.default_web_client_id)
                    if (resId.isNotBlank() && !resId.contains("qcssk9mifnubqqj1v7s0i55iff5eqrhd")) resId else GOOGLE_WEB_CLIENT_ID
                } catch (e: Exception) {
                    GOOGLE_WEB_CLIENT_ID
                }

                val clientIdsToTry = listOf(
                    GOOGLE_WEB_CLIENT_ID,
                    defaultWebClientId
                ).distinct()

                AppLogger.i("SignInScreen", "Resolved client IDs: $clientIdsToTry")

                var credentialResult: Credential? = null
                var lastException: Throwable? = null
                var isUserCancelled = false

                for (clientId in clientIdsToTry) {
                    if (credentialResult != null || isUserCancelled) break

                    // 1. Primary Strategy: GetGoogleIdOption (standard modern Credential Manager)
                    AppLogger.i("SignInScreen", "Trying GetGoogleIdOption with clientId: $clientId")
                    try {
                        val googleIdOption = GetGoogleIdOption.Builder()
                            .setFilterByAuthorizedAccounts(false)
                            .setServerClientId(clientId)
                            .setAutoSelectEnabled(false)
                            .build()

                        val request = GetCredentialRequest.Builder()
                            .addCredentialOption(googleIdOption)
                            .build()

                        statusMessage = "يرجى اختيار حساب Google..."
                        val response = withTimeoutOrNull(25_000L) {
                            credentialManager.getCredential(request = request, context = activity)
                        }

                        if (response != null) {
                            credentialResult = response.credential
                            AppLogger.i("SignInScreen", "GetGoogleIdOption succeeded with clientId: $clientId")
                            break
                        } else {
                            AppLogger.w("SignInScreen", "GetGoogleIdOption timed out (25s) with clientId: $clientId")
                        }
                    } catch (e: GetCredentialCancellationException) {
                        AppLogger.w("SignInScreen", "User dismissed or cancelled Google Sign-In picker.")
                        isUserCancelled = true
                        break
                    } catch (e: Throwable) {
                        AppLogger.w("SignInScreen", "GetGoogleIdOption failed with $clientId: ${e::class.java.simpleName}: ${e.message}")
                        lastException = e
                    }

                    if (credentialResult != null || isUserCancelled) break

                    // 2. Secondary Strategy: GetSignInWithGoogleOption as fallback
                    AppLogger.i("SignInScreen", "Trying GetSignInWithGoogleOption fallback with clientId: $clientId")
                    try {
                        val signInWithGoogleOption = GetSignInWithGoogleOption.Builder(serverClientId = clientId)
                            .build()

                        val request = GetCredentialRequest.Builder()
                            .addCredentialOption(signInWithGoogleOption)
                            .build()

                        statusMessage = "يرجى اختيار حساب Google..."
                        val response = withTimeoutOrNull(25_000L) {
                            credentialManager.getCredential(request = request, context = activity)
                        }

                        if (response != null) {
                            credentialResult = response.credential
                            AppLogger.i("SignInScreen", "GetSignInWithGoogleOption succeeded with clientId: $clientId")
                            break
                        } else {
                            AppLogger.w("SignInScreen", "GetSignInWithGoogleOption timed out (25s) with clientId: $clientId")
                        }
                    } catch (e: GetCredentialCancellationException) {
                        AppLogger.w("SignInScreen", "User dismissed or cancelled Google Sign-In picker on fallback.")
                        isUserCancelled = true
                        break
                    } catch (e: Throwable) {
                        AppLogger.w("SignInScreen", "GetSignInWithGoogleOption failed with $clientId: ${e::class.java.simpleName}: ${e.message}")
                        lastException = e
                    }
                }

                if (isUserCancelled) {
                    isLoading = false
                    statusMessage = null
                    errorMessage = "تم إغلاق نافذة اختيار حساب Google. اضغط على الزر مجدداً واختر حسابك للمتابعة."
                    return@launch
                }

                if (credentialResult == null) {
                    isLoading = false
                    statusMessage = null
                    val msg = when (lastException) {
                        is NoCredentialException -> "لا يوجد حساب Google مسجّل على هذا الجهاز. يرجى تسجيل الدخول إلى حساب Google من إعدادات الجهاز أولاً ثم إعادة المحاولة."
                        is GetCredentialException -> "تعذر استرداد بيانات حساب Google (${lastException.message ?: lastException.type}). يرجى التحقق من اتصال الإنترنت."
                        null -> "استغرق تسجيل الدخول عبر Google وقتاً طويلاً دون استجابة. يرجى إعادة المحاولة."
                        else -> "حدث خطأ أثناء تسجيل الدخول عبر Google: ${lastException.message}"
                    }
                    errorMessage = msg
                    return@launch
                }

                val credential = credentialResult
                AppLogger.i("SignInScreen", "Response received! Credential class=${credential::class.java.name}, type=${credential.type}")
                if (credential is CustomCredential) {
                    val keySet = credential.data.keySet()?.joinToString() ?: "empty"
                    AppLogger.i("SignInScreen", "CustomCredential bundle keys: $keySet")
                }

                if (credential is CustomCredential && credential.type == GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL) {
                    AppLogger.i("SignInScreen", "Type matches GoogleIdTokenCredential. Calling GoogleIdTokenCredential.createFrom...")
                    val googleIdTokenCredential = GoogleIdTokenCredential.createFrom(credential.data)
                    val idToken = googleIdTokenCredential.idToken
                    val email = googleIdTokenCredential.id
                    val displayName = googleIdTokenCredential.displayName
                    AppLogger.i("SignInScreen", "Token extracted successfully! email=$email, idTokenLength=${idToken.length}, displayName=$displayName")
                    statusMessage = "جاري التحقق من الحساب والاشتراك..."
                    AppLogger.i("SignInScreen", "Dispatching onSignInSuccess(idToken, email, displayName)")
                    onSignInSuccess(idToken, email, displayName)
                } else {
                    AppLogger.e("SignInScreen", "Credential type mismatch! Expected: ${GoogleIdTokenCredential.TYPE_GOOGLE_ID_TOKEN_CREDENTIAL}, Actual: ${credential.type}")
                    isLoading = false
                    statusMessage = null
                    errorMessage = "فشل التعرف على بيانات الاعتماد من Google (${credential.type})."
                }
            } catch (e: Throwable) {
                isLoading = false
                statusMessage = null
                AppLogger.e("SignInScreen", "Unexpected Throwable during sign-in: Class=${e::class.java.name}, Message=${e.message}, Cause=${e.cause}", e)
                errorMessage = "حدث خطأ غير متوقع أثناء تسجيل الدخول: ${e.message}"
            }
        }
    }

    Scaffold(
        containerColor = BackgroundPure,
        contentWindowInsets = WindowInsets.safeDrawing
    ) { innerPadding ->
        Column(
            modifier = Modifier
                .fillMaxSize()
                .padding(innerPadding)
                .padding(horizontal = 24.dp)
                .verticalScroll(rememberScrollState()),
            horizontalAlignment = Alignment.CenterHorizontally,
            verticalArrangement = Arrangement.SpaceBetween
        ) {
            if (onBack != null) {
                Row(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(top = 8.dp),
                    horizontalArrangement = Arrangement.Start
                ) {
                    IconButton(
                        onClick = onBack,
                        modifier = Modifier.testTag("signin_back_button")
                    ) {
                        Icon(
                            imageVector = Icons.AutoMirrored.Filled.ArrowBack,
                            contentDescription = "الرجوع",
                            tint = TextSecondary
                        )
                    }
                }
            } else {
                Spacer(modifier = Modifier.height(24.dp))
            }

            // Hero mascot & branding
            Column(
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(16.dp)
            ) {
                // Sticker-style Katzu mascot placed directly on AMOLED black
                Image(
                    painter = painterResource(id = R.drawable.katzu_peace),
                    contentDescription = "كاتزو",
                    modifier = Modifier.size(140.dp),
                    contentScale = ContentScale.Fit
                )

                Text(
                    text = "مرحباً بك مجدداً",
                    style = MaterialTheme.typography.headlineMedium,
                    fontFamily = Cairo,
                    fontWeight = FontWeight.Bold,
                    color = TextPrimary,
                    textAlign = TextAlign.Center
                )

                Text(
                    text = "سجّل دخولك بحساب Google لنحفظ مسار محادثاتك وتقدمك واشتراكك أينما تنقّلت.",
                    style = MaterialTheme.typography.bodyMedium,
                    fontFamily = Cairo,
                    color = TextSecondary,
                    textAlign = TextAlign.Center,
                    lineHeight = 24.sp,
                    modifier = Modifier.padding(horizontal = 12.dp)
                )
            }

            // Central card
            Card(
                modifier = Modifier
                    .fillMaxWidth()
                    .border(1.dp, Color(0x14F2F0F7), RoundedCornerShape(20.dp)),
                shape = RoundedCornerShape(20.dp),
                colors = CardDefaults.cardColors(containerColor = SurfaceCard)
            ) {
                Column(
                    modifier = Modifier
                        .fillMaxWidth()
                        .padding(20.dp),
                    horizontalAlignment = Alignment.CenterHorizontally,
                    verticalArrangement = Arrangement.spacedBy(14.dp)
                ) {
                    Text(
                        text = "الخصوصية والحفظ التلقائي",
                        fontFamily = Cairo,
                        fontWeight = FontWeight.Bold,
                        fontSize = 16.sp,
                        color = TextPrimary
                    )

                    Text(
                        text = "محادثاتك ومستواك في أمان تام، مع ربط فوري وموثوق بحسابك دون كلمات مرور إضافية.",
                        fontFamily = Cairo,
                        fontSize = 13.sp,
                        color = TextMuted,
                        textAlign = TextAlign.Center,
                        lineHeight = 20.sp
                    )

                    if (errorMessage != null) {
                        Surface(
                            color = StatusError.copy(alpha = 0.15f),
                            shape = RoundedCornerShape(12.dp),
                            border = androidx.compose.foundation.BorderStroke(1.dp, StatusError.copy(alpha = 0.5f)),
                            modifier = Modifier.fillMaxWidth()
                        ) {
                            Column(
                                modifier = Modifier.padding(12.dp),
                                horizontalAlignment = Alignment.CenterHorizontally,
                                verticalArrangement = Arrangement.spacedBy(8.dp)
                            ) {
                                Text(
                                    text = errorMessage ?: "",
                                    color = StatusError,
                                    fontFamily = Cairo,
                                    fontSize = 12.sp,
                                    textAlign = TextAlign.Center
                                )

                                if (com.example.katzu.BuildConfig.DEBUG) {
                                    Row(
                                        horizontalArrangement = Arrangement.spacedBy(8.dp),
                                        verticalAlignment = Alignment.CenterVertically
                                    ) {
                                        OutlinedButton(
                                            onClick = { AppLogger.copyLastLinesToClipboard(context, 40) },
                                            shape = RoundedCornerShape(14.dp),
                                            contentPadding = PaddingValues(horizontal = 12.dp, vertical = 4.dp),
                                            border = androidx.compose.foundation.BorderStroke(1.dp, StatusError.copy(alpha = 0.6f))
                                        ) {
                                            Text(
                                                text = "نسخ تفاصيل الخطأ",
                                                fontFamily = Cairo,
                                                fontSize = 11.sp,
                                                color = TextPrimary
                                            )
                                        }

                                        OutlinedButton(
                                            onClick = { AppLogger.shareLogFile(context) },
                                            shape = RoundedCornerShape(14.dp),
                                            contentPadding = PaddingValues(horizontal = 12.dp, vertical = 4.dp),
                                            border = androidx.compose.foundation.BorderStroke(1.dp, Primary.copy(alpha = 0.6f))
                                        ) {
                                            Text(
                                                text = "إرسال السجل",
                                                fontFamily = Cairo,
                                                fontSize = 11.sp,
                                                color = Primary
                                            )
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }

            // Google Sign-In Action Button
            Column(
                modifier = Modifier
                    .fillMaxWidth()
                    .padding(bottom = 24.dp),
                horizontalAlignment = Alignment.CenterHorizontally,
                verticalArrangement = Arrangement.spacedBy(12.dp)
            ) {
                Button(
                    onClick = { triggerGoogleSignIn() },
                    enabled = !isLoading,
                    modifier = Modifier
                        .fillMaxWidth()
                        .height(52.dp)
                        .testTag("google_sign_in_button"),
                    shape = RoundedCornerShape(26.dp),
                    colors = ButtonDefaults.buttonColors(
                        containerColor = Primary,
                        contentColor = TextPrimary
                    )
                ) {
                    if (isLoading) {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(10.dp)
                        ) {
                            CircularProgressIndicator(
                                modifier = Modifier.size(20.dp),
                                color = TextPrimary,
                                strokeWidth = 2.dp
                            )
                            Text(
                                text = statusMessage ?: "جاري المعالجة...",
                                fontFamily = Cairo,
                                fontWeight = FontWeight.Bold,
                                fontSize = 14.sp,
                                color = TextPrimary
                            )
                        }
                    } else {
                        Row(
                            verticalAlignment = Alignment.CenterVertically,
                            horizontalArrangement = Arrangement.spacedBy(10.dp)
                        ) {
                            Text(
                                text = "G",
                                fontFamily = Cairo,
                                fontWeight = FontWeight.Bold,
                                fontSize = 20.sp,
                                color = TextPrimary
                            )
                            Text(
                                text = "تسجيل الدخول باستخدام Google",
                                fontFamily = Cairo,
                                fontWeight = FontWeight.Bold,
                                fontSize = 15.sp,
                                color = TextPrimary
                            )
                        }
                    }
                }

                if (isLoading) {
                    TextButton(
                        onClick = {
                            isLoading = false
                            statusMessage = null
                            AppLogger.i("SignInScreen", "User tapped cancel loading")
                        },
                        modifier = Modifier.testTag("signin_cancel_loading_button")
                    ) {
                        Text(
                            text = "إلغاء والمحاولة مرة أخرى",
                            fontFamily = Cairo,
                            color = TextMuted,
                            fontSize = 13.sp
                        )
                    }
                }

                Text(
                    text = "صُنع بواسطة غيدق علوش — ghaidak.com",
                    fontFamily = Cairo,
                    fontSize = 11.sp,
                    color = TextMuted
                )
            }
        }
    }
}
